### PR TITLE
ESP8266 build

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
Introduce compatibility wrappers for newly used APIs. GPIO- and RTC-GPIO-related.

### CODE REVIEW

**Comment by revk** [comment]
I'll look when I get back to the hotel...

Looks mostly sane.

I hope you like the new settings stuff...

**Comment by Sonic-Amiga** [comment]
It's nice, however this PR will grow. USE_OLD_SETTINGS defaulted to Y for me; and after disabling i got a new bunch of compile errors.

**Comment by revk** [comment]
Yeh the scripts turn it off if you have a settings.def file, which you need to include in your make file.

**Comment by revk** [comment]
Several more tweaks planned for today, hopefully won't break much.

**Pull request merged**
