### PR TITLE
ESP8266 support and improvements

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
Changes and fixes to build under ESP8266 v3 SDK. Some API wrappers, some fixes for build without websockets, some more general fixes

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello dear friend!
First of all, thank you very much for your Faikin project. I am currently working on porting it to ESP8266 (because i have the hardware), and i'd like to contribute. Please take a look, i hope you're interested.

My main project is here: https://github.com/Sonic-Amiga/ESP8266-Faikin . It's still a work in progress; and if you're interested, i can contribute part of it back to your project too. The main improvement is better implementation of a protocol, compatible with original BRP series online controller.

**Review by revk — COMMENTED** [review]
The use of %ld not %d was specifically because of compiler warnings requiring %ld so rather concerned at them being removed. Have you build thugs as an ESP32 target?

**Comment by revk** [comment]
I'm interested in any better understanding of the Daikin protocol, for sure.

I see the library changes, not 100% sure on the %ld/%d changes though.

**Comment by Sonic-Amiga** [comment]
Okay, no problem, i'll redo this in a different way.
I didn't test ESP32 build indeed, being too lazy, sorry for that. I verified against ESP32 SDK docs; and they also claim functions in question to return uint32_t; and uint32_t should be %d in fact, because 32-bit isn't 'long'. So a bit unexpected. Thank you for pointing out.

**Comment by revk** [comment]
Indeed, I thought it odd at the time as well.

**Comment by Sonic-Amiga** [comment]
As to protocol understanding, you'll get it. Because Faikin doesn't appear to work with my FTXF20D; so a reverse-engineering adventure is ahead. It looks like i'll write an AC simulator specifically for this purpose.

**Comment by revk** [comment]
Indeed top level `faikin.c` was for that purpose :-)

**Comment by Sonic-Amiga** [comment]
Updated the PR regarding long's, what about this approach ? Also squashed things a bit.

BTW, note the patchset also fixes an original bug: pressing Set in wifi settings page with "as is" as password didn't do the job; because the string is sent as "as+is" and not decoded back by the framework. Logically it should also be the case on esp32.

**Comment by Sonic-Amiga** [comment]
> `faikin.c` was for that purpose

Thank you ve-e-e-ry much for pointing out!

**Comment by revk** [comment]
Yes, the `(long)` seems a sensible way to handle it.

**Review by revk — COMMENTED** [review]
Actually, setbuildsuffix will need to do the idf.py command to change to ESP8266 won't it.

So maybe what you suggest is sensible. Or we could make setbuildsuffix do the change if needed.

I'll go with what you suggest for now.

**Comment by Sonic-Amiga** [comment]
> Actually, setbuildsuffix will need to do the idf.py command to change to ESP8266 won't it.

 Sorry, i don't exactly understand you.
CONFIG_IDF_TARGET_ESP8266 is set by the SDK itself. As far as i understood, idf.py calls 'buildsuffix', not 'setbuildsuffix'. The latter is only called manually to change the target SoC, and that can't be done on 8266

**Comment by Sonic-Amiga** [comment]
The build works fine (don't pay attention to "cannot touch" as of now):
```
$ make
touch: cannot touch '/d/Projects/ESP8266_RTOS_SDK/components/esp_app_format/esp_app_desc.c': No such file or directory
Makefile:27: mariadb/mysql not installed, needed for tools
Make: Faikin-8266.bin
Checking Python dependencies...
Python requirements from D:/Projects/ESP8266_RTOS_SDK/requirements.txt are satisfied.
Executing action: all (aliases: build)
Running ninja in directory d:/projects/esp8266-faikin/build
Executing "ninja all"...
[1/8] Performing build step for 'bootloader'
ninja: no work to do.
[8/8] Generating binary image from built executable
esptool.py v2.4.0
Generated D:/Projects/ESP8266-Faikin/build/Faikin.bin

Project build complete. To flash, run this command:
../ESP8266_RTOS_SDK/components/esptool_py/esptool/esptool.py -p (PORT) -b 460800 --after hard_reset write_flash --flash_mode dio --flash_size 8MB --flash_freq 40m 0x0 build/bootloa
der/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0xd000 build/ota_data_initial.bin 0x10000 build/Faikin.bin
or run 'idf.py -p (PORT) flash'
Done: Faikin-8266.bin

Sonic@Sonic MINGW64 /d/Projects/ESP8266-Faikin
$ make pico
touch: cannot touch '/d/Projects/ESP8266_RTOS_SDK/components/esp_app_format/esp_app_desc.c': No such file or directory
Makefile:27: mariadb/mysql not installed, needed for tools
components/ESP32-RevK/setbuildsuffix -S1-PICO
setbuildsuffix is not supported on ESP8266
make: *** [Makefile:50: pico] Error 255
```

**Comment by Sonic-Amiga** [comment]
Anyways 8266 is still a different SDK, so you cannot cross-build for ESP32 using it; and vice versa.

https://github.com/espressif/ESP8266_RTOS_SDK , if you want to take a look

**Comment by revk** [comment]
Yes, initially I was thinking one would just do `setbuildsuffix whatever-ESP8266`

But as you set you have to set the build target to ESP8266 (presumably with `idf.py`).

So yes, what you are doing makes sense.

**Comment by revk** [comment]
Oh, totally separate SDK, OK, that adds to the fun.

The `touch` on `components/esp_app_format/esp_app_desc.c` is to force a fresh date time in every build. I assume there is an equiv for ESP8266? Checking if ESP8266 and doing something different in that script is probably sensible.

**Comment by Sonic-Amiga** [comment]
I know what that touch does. Since everything has an equivalent, that should also have an equivalent, i simply don't care at the moment because i have different things to do

**Comment by revk** [comment]
OK.

I'll merge.

**Comment by revk** [comment]
Screenshot 2023-06-18 at 13 07 25
Grr

**Comment by revk** [comment]
OK updating now.

**Comment by Sonic-Amiga** [comment]
Doh, my bad! See REQUIRES line change. Should have been surrounded by if().
I postponed it and of course forgot

**Comment by Sonic-Amiga** [comment]
There's already an if(), just introduce a var, like SDK_COMPONENTS, and put two variants there

**Comment by revk** [comment]
Hmm
```
../components/ESP32-RevK/include/revk.h:12:10: fatal error: esp_wifi.h: No such file or directory
   12 | #include "esp_wifi.h"
      |          ^~~~~~~~~~~~
```

**Comment by Sonic-Amiga** [comment]
Okay, give me a try

**Comment by revk** [comment]
I got this, just a sec

**Comment by revk** [comment]
OK how does that look?

**Comment by Sonic-Amiga** [comment]
Working on this; it's a bit quirky.

**Comment by revk** [comment]
I think that `CMakeLists.txt` I have done now is simpler now. If it works for you, good. It is working for me for ESP32.

**Comment by Sonic-Amiga** [comment]
Okay, let's leave it as it is.
There's a quirk there. Dependencies are collected before any CONFIG_* vars are evaluated. So for me it's also false. So i get wrong list.
Let's consider it a TODO. Perhaps i need to study more about build system internals.

**Comment by Sonic-Amiga** [comment]
Thank you for cooperation! I have to run soon, see you later.

**Comment by revk** [comment]
I wondered about that - I assumed your CONFIG test worked, but oddly my attempt to do the same for MDNS did not. If you can find another way to test for being 8266, that makes sense... As you see, I am using a file existing.

**Comment by revk** [comment]
Anyway thanks for the input, nice that the other dependancies (`lwmqtt`, etc) are working for ESP8266 though.

**Pull request merged**
