### PR TITLE
revk: Fetch app descriptor from accompanying .desc file in 8266

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
ESP8266 uses image header v1, which doesn't store versioning info. This caused endless cyclic updates, because version never matches.

Read the required info in the form of esp_app_desc_t structure from dedicated file, accompanying the main binary. This is the easiest way.

The change also improves ESP32 version check by magic word verification. This should protect against corrupt binaries (for whatever reason).

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello! I have tested this on both platforms; but given critical nature of this change please retest it once more. Just in case.

**Comment by revk** [comment]
I'll go through it later.

**Comment by revk** [comment]
It all looks sane, but as you say, need to do lots of testing!

**Comment by revk** [comment]
I'll make a beta, presumably we need the `.desc` file for 8266?

**Comment by Sonic-Amiga** [comment]
Yes we do. I have the code to produce it in my repo; i will make a proper release after testing in my home. It will take a day or two. Lesson learned.

**Pull request merged**
