### PR TITLE
revk_settings: Fix "array subscript has type ‘char’" warning

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
According to C standard, isXXXX() functions has an int argument, but the character value must be positive. Calling them on char argument violates this rule by sign-extending char (which is signed) to int. This may potentially even cause crash by dereferencing random memory if we happen to have some national or UTF-8 long characters in our settings.def

Some libc implementations signal the potential problem using this warning

### CODE REVIEW

**Comment by revk** [comment]
I usually build thing with unsigned char, but I bet that is not the default in the ESP IDF.

Always struck me as specially stupid that isXXX does not take a char argument as it is for identifying chars, FFS.

**Comment by Sonic-Amiga** [comment]
That's me again. Instead of fighting the reality and rewriting all the auxiliary tools in python, i have come up with a way to employ some help of Cygwin or MSys when building Faikin on Windows using a wrapper script. It turns out that compiling the settings processor for these targets yields the aforementioned warning.

If you're interested how it's done, this is a snip from ctype.h:
```
/* These macros are intentionally written in a manner that will trigger
   a gcc -Wall warning if the user mistakenly passes a 'char' instead
   of an int containing an 'unsigned char'.  Note that the sizeof will
   always be 1, which is what we want for mapping EOF to __CTYPE_PTR[0];
   the use of a raw index inside the sizeof triggers the gcc warning if
   __c was of type char, and sizeof masks side effects of the extra __c.
   Meanwhile, the real index to __CTYPE_PTR+1 must be cast to int,
   since isalpha(0x100000001LL) must equal isalpha(1), rather than being
   an out-of-bounds reference on a 64-bit machine.  */
#define __ctype_lookup(__c) ((__CTYPE_PTR+sizeof(""[__c]))[(int)(__c)])

#define	isalpha(__c)	(__ctype_lookup(__c)&(_U|_L))
#define	isupper(__c)	((__ctype_lookup(__c)&(_U|_L))==_U)
#define	islower(__c)	((__ctype_lookup(__c)&(_U|_L))==_L)
#define	isdigit(__c)	(__ctype_lookup(__c)&_N)
#define	isxdigit(__c)	(__ctype_lookup(__c)&(_X|_N))
#define	isspace(__c)	(__ctype_lookup(__c)&_S)
#define ispunct(__c)	(__ctype_lookup(__c)&_P)
#define isalnum(__c)	(__ctype_lookup(__c)&(_U|_L|_N))
#define isprint(__c)	(__ctype_lookup(__c)&(_P|_U|_L|_N|_B))
#define	isgraph(__c)	(__ctype_lookup(__c)&(_P|_U|_L|_N))
#define iscntrl(__c)	(__ctype_lookup(__c)&_C)
```
I know this is very surprising, because these functions feel like they are designed to work on chars, yet that's not the case.
More info:
https://stackoverflow.com/questions/10186219/array-subscript-has-type-char - a question about this
https://linux.die.net/man/3/isdigit - official manual, which explicitly says:
```
c, which must have the value of an unsigned char or EOF
```

**Comment by revk** [comment]
This may be better as functions or macros in revk.h and revk.c than just for settings.

**Comment by revk** [comment]
I'll look in the morning, as this is a more general issue, and also WTAF do they literally have `(int)(__c)` and not `(unsigned char)(__c)` in that macro?!

**Comment by revk** [comment]
I never need to look for EOF, to will make macros to cast to unsigned char and include in revk.h as check various code for this - more than just settings stuff. Thanks for pointing out the stupidity.

**Comment by revk** [comment]
I have added `-funsigned-char` for that code, and added macros for ESP IDF code.

**Pull request closed without merging**
